backend:
  name: github
  repo: zakfarnworth23/farnworthdotorguk25
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "statements"
    label: "Statements"
    folder: "content/statements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
